### ISSUE TITLE
Hexcasting compatibility patch

### ISSUE THREAD

**Issue by Woof6968** [dragon-forge/BotanicAdditions#1]
Whenever you look at the gaia agglomeration plate while wearing the scrying lens from hexcasting, it is meant to show information to help with redstone comparators, but the game kicks you when you look at a gaia agglomeration platewhile using the lens.

[Stack trace](https://pastebin.com/raw/EQ3hjw5p)

**Comment by Zeitheron** [comment]
I can not extend TerrestrialAgglomerationPlateBlockEntity, thus this issue should be reported to hexcasting devs.

**Comment by Zeitheron** [comment]
Does putting a comparator crash like that?

**Comment by Woof6968** [comment]
not sure

**Comment by Woof6968** [comment]
yep, it does the same with a normal comparator

**Comment by Zeitheron** [comment]
Alright, will resolve it in next patch.
