### ISSUE TITLE
Rune of Energy does not consume runes used in recipe on FTB Skies

### ISSUE THREAD

**Issue by CircuitSage** [dragon-forge/BotanicAdditions#11]
The Rune of Fire and the Rune of Air both are returned on use. Not sure if this behavior is intended, or if it's an issue with the modpack recipe, but just making sure it's reported just in case.

**Comment by LandofHeros2234** [comment]
Runes used in Rune crafting are returned, it says so in the Lexica Botania, so yes, this is works as intended
