### ISSUE TITLE
Recipes are impossible to edit

### ISSUE THREAD

**Issue by TheDrOfDoctoring** [dragon-forge/BotanicAdditions#6]
**Tested on 1.19.2, mod version 19.3.3.** 

When trying to remove the recipes for the Mana Tesseract, Elven Fluxfield and flowers with KubeJS, I realized that it was seemingly impossible to remove these from methods in kubejs.
Then, I tried by removing them manually through a datapack, to discover it also seems impossible that way.

This is an issue as, at least for me, a pack developer might not want every feature from the mod to be available or at least to restrict the features of the mod to a different progression.

If you want to test this with KubeJS, you can replicate it with this inside of a server script 
```
ServerEvents.recipes(event => { 
   event.remove({id: 'botanicadds:elven_fluxfield'})
  event.remove({id: 'botanicadds:flowers/energizera'})
})
```

**Comment by Zeitheron** [comment]
I made a JSON config file in `/config/botanicadds/recipes.json` for next build, where each recipe can be toggled off.
In 1.20 and going forward, all of my mods recipes will be handled through `/config/hammerlib/recipes/modded/<mod_id>.json`

**Comment by Leclowndu93150** [comment]
WAIT WHAT WHY ??? can't you use datapack recipes like every other mod ? that would make our work easier
