### ISSUE TITLE
[1.19.2] Crash when placing Rainute

### ISSUE THREAD

**Issue by HockeyZman2000** [dragon-forge/BotanicAdditions#7]
[crash-2023-05-15_17.28.43-client.txt](https://github.com/dragon-forge/BotanicAdditions/files/11482417/crash-2023-05-15_17.28.43-client.txt)

I got this crash when attempting to place the Rainute flower

Botanic Additions Version 19.3.3
Forge Version 43.2.11

**Comment by Zeitheron** [comment]
Was this an issue in prior versions of Botania?

**Comment by Zeitheron** [comment]
It seems like the new update of Botania has broken the constructor, I will release a patch addressing this issue shortly.
