### ISSUE TITLE
make recipes json recipe

### ISSUE THREAD

**Issue by Joshernoob** [dragon-forge/BotanicAdditions#9]
Make recipe json ones so they can be changed or added to like the mod this is adding to itself

currently recipes seem to be .java files and all mods that change recipes without the mod auther doing extra work use .json recipe or datapack recipe system

example is kubejs uses its own data packs that it loads it a folder as if minecraft was loading them ,while crafttweaker adds the recipes as if there part of its own mod still using data pack just part of its own

don't need to add custom saport just make the recipes visable for people to see and pack creators can do the rest

**Comment by Zeitheron** [comment]
Use configs to turn off the recipes if  you want to tweak them.

**Comment by merfed** [comment]
There are no configs to turn off the recipes, how can recipes be disabled?

**Comment by Zeitheron** [comment]
> There are no configs to turn off the recipes, how can recipes be disabled?

configs/hammerlib/recipes/
